
version: '3'
services:
  app:
    container_name: penumbra:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9012:9012"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development