
version: '3'
services:
  app:
    container_name: penumbra
    image: penumbra:latest  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7073:7073"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development