---
# Builts a fresh container of the app code, then deploys that container
# to the testnet cluster, at:
# https://app.testnet.penumbra.zone
name: Deploy dapp site
on:
  # Support ad-hoc runs via dispatch, so we can deploy from
  # unmerged feature branches if necessary.
  workflow_dispatch:
  push:
    branches:
      - main
  # Uncomment to run on PRs; useful while debugging.
  # pull_request:
jobs:
# TODO: build container via dispatch, and set dependency on build job.
#  container:
#    name: Build container for dapp
#    uses: ./.github/workflows/container.yml
#    secrets: inherit
  deploy:
    name: Deploy dapp website to cluster
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Configure gcloud auth
        id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: Configure GKE auth
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      - name: Bounce dapp deployment
        run: kubectl rollout restart deployment dapp
